### PR TITLE
Warnings for all unformatted files

### LINKED ISSUE #17: Generate warnings for all unformatted files when running scalafmtCheck
Currently `scalafmtCheck` generates an error for the first unformatted file found and fails the task. My suggestion is to have an ability to generate warnings for all unformatted files instead.

I think this may allow cleaner integration into development process by hinting the developer to run the formatter without being overly intrusive (as opposed to `scalafmtOnCompile`).

This behavior may be controlled by options, e.g. existing runner.fatalWarnings or a new flag.

Another good idea is to pair this with incremental formatting.

### PR DESCRIPTION
**Pull request by poslegm**
Fixes #17 

Current behavior is very uncomfortable for me too.

Why was this not done earlier? Can this change harm the user experience in a case that I didn't think of?

### CODE REVIEW

File: plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala [hunk 1]
```diff
@@ -153,7 +153,7 @@ object ScalafmtPlugin extends AutoPlugin {
     cached[Boolean](cacheDirectory, FilesInfo.lastModified) { modified =>
       val changed = modified.filter(_.exists)
       if (changed.size > 0) {
-        log.info(s"Formatting ${changed.size} Scala sources...")
+        log.info(s"Checking ${changed.size} Scala sources...")
```
Comment (tanishiking) [inline plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala]: Nice :+1:
