### PR TITLE
Managed sources filter

### LINKED ISSUE #51: [2.0.4+] Managed sources from meta builds should not be formatted/checked
### Steps to reproduce

Set up a basic project where the meta build has managed sources (in this case, a dummy twirl Scala template)

`.scalafmt.conf`
```
version = 2.0.0
```

`project/plugins.sbt`
```
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.6")
```

`project/build.sbt`
```
lazy val root = (project in file("."))
  .enablePlugins(SbtTwirl)
```

`project/src/main/twirl/template.scala.txt`
```
```

`project/project/plugins.sbt`
```
addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.4.2")
```

### Actual
```
bjaglin@x1:/tmp/sbt-project$ sbt scalafmtSbtCheck
[info] Loading settings for project global-plugins from idea.sbt,build.sbt ...
[info] Loading global plugins from /home/bjaglin/.sbt/1.0/plugins
[info] Loading settings for project sbt-project-build-build from plugins.sbt ...
[info] Loading project definition from /tmp/sbt-project/project/project
[info] Loading settings for project root from plugins.sbt,build.sbt ...
[info] Loading project definition from /tmp/sbt-project/project
[info] Set current project to sbt-project (in build file:/tmp/sbt-project/)
[info] Checking 3 Scala sources...
[info] Checking 1 Scala sources...
[warn] /tmp/sbt-project/project/target/scala-2.12/sbt-1.0/twirl/main/txt/template.template.scala isn't formatted properly!
[error] 1 files must be formatted
[error] (Compile / scalafmtSbtCheck) 1 files must be formatted
[error] Total time: 2 s, completed Sep 30, 2019, 10:23:57 PM
```

### Expected
`sbt scalafmtSbtCheck` succeeds - managed sources are ignored.

### Real-world scenario
[Akka-gRPC](https://github.com/akka/akka-grpc) supports custom code generation from protobuf files.

### PR DESCRIPTION
**Pull request by poslegm**
Fixes #51

We ignore `target` directory content by default. If you need to ignore another directory with managed sources you can use `project.excludeFilters` in the configuration.

### CODE REVIEW

**Comment by bjaglin** [comment]
That's pretty much what I had in mind for the second bullet of https://github.com/scalameta/sbt-scalafmt/issues/51#issuecomment-536763335 :+1:

File: plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala [hunk 1]
```diff
@@ -271,7 +271,16 @@ object ScalafmtPlugin extends AutoPlugin {
...
     if (rootBase == thisBase)
-      (BuildPaths.projectStandard(thisBase) ** GlobFilter("*.scala")).get
+      BuildPaths
+        .projectStandard(thisBase)
+        .descendantsExcept(
+          "*.scala",
+          (pathname: File) =>
+            pathname.getAbsolutePath
+              .drop(thisBase.getAbsolutePath.length)
+              .contains("/target/")
```
Comment (tanishiking) [inline plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala]: Maybe we can use [outputDirectory(projectStandard(thisBase))](https://github.com/sbt/sbt/blob/a8e319e97b3c800915382e2c9528edf7a54efb65/main/src/main/scala/sbt/BuildPaths.scala#L121) for filtering them.

**Comment by tanishiking** [comment]
> scalafmtIgnorePath := (pathname: File) => pathname.getName == "ignore.txt"

Since scalafmtDynamic respects the `project.excludeFilters` option, I think we don't need to expose such API?
https://github.com/scalameta/scalafmt/blob/c1923bc7e6b621872f06a2b652e34679e61fa06f/scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala#L207

File: plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala (hunk 1 above)
Comment (poslegm) [reply plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala]: Thank you so much, I didn't know about it!

**Comment by poslegm** [comment]
@tanishiking Yes, you are right. I forgot about `excludeFilters` but it is the best solution.

File: plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala [hunk 2]
```diff
@@ -270,9 +270,22 @@ object ScalafmtPlugin extends AutoPlugin {
...
     val thisBase = (thisProject.value).base
-    if (rootBase == thisBase)
-      (BuildPaths.projectStandard(thisBase) ** GlobFilter("*.scala")).get
-    else Nil
+
+    if (rootBase == thisBase) {
+      val projectDirectory = BuildPaths.projectStandard(thisBase)
+      val targetDirectory =
+        BuildPaths.outputDirectory(projectDirectory).getAbsolutePath
+      println(projectDirectory)
```
Comment (tanishiking) [inline plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala]: Debug print remains

File: plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala [hunk 3]
```diff
@@ -270,9 +270,22 @@ object ScalafmtPlugin extends AutoPlugin {
...
+      projectDirectory
+        .descendantsExcept(
+          "*.scala",
+          (pathname: File) =>
+            pathname.getAbsolutePath.startsWith(targetDirectory)
```
Comment (bjaglin) [inline plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala]: I guess this will not exclude target directories from meta-meta builds?

File: plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala (hunk 2 above)
Comment (poslegm) [reply plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala]: Oh, thank you

File: plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala (hunk 3 above)
Comment (poslegm) [reply plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala]: I think that `project.excludeFilters` would be enough for this
